### ISSUE TITLE
Create Carousel Navigation Component

### ISSUE THREAD

**Issue by nurselaine** [PhitNest/umee-web#9]
**Description**:

- Develop a carousel navigation component that matches the design specifications provided in the Figma design.
- The carousel navigation component should include navigation arrows or dots to allow users to navigate between carousel items.
- Ensure that the navigation component aligns with the overall design theme and aesthetics of the website.
- Implement functionality to enable users to interact with the navigation component and navigate between carousel items seamlessly.
- Customize the appearance of the navigation component to match the styling and color scheme specified in the design.

**Completion Criteria**:

- Carousel navigation component is implemented according to the design specifications provided in the Figma design.
- Navigation component includes clear and intuitive navigation dots for users to interact with.
- Navigation controls are functional and allow users to navigate between carousel items smoothly.
- The appearance and styling of the navigation component match the overall design theme of the website.
- Verify that the navigation component is responsive and displays correctly across different screen sizes and devices.
- Test the navigation component for usability and ensure that it provides a seamless user experience.

**Comment by CaglarKullu** [comment]
![image](https://github.com/PhitNest/umee-web/assets/97615706/fa67b6b3-d096-446c-bee7-cbce8e91affb)
Please check the branch
